import Head from 'next/head'
import matter from 'gray-matter'
import fs from 'fs'
import path from 'path'
import Post from '../components/Post'
import { sortByDate } from '../utils'

export default function Home({ posts }) {

  return (
    <div>
      <Head>
        <title>Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="posts">
        {posts.map((post, index) => (
          <Post post={post} key={index} />
        ))}
      </div>
    </div>
  )
}


export async function getStaticProps() {
  //runs server side

  //gets files from posts dir
  const files = fs.readdirSync(path.join('posts'))

  //get slug and front matter from posts 
  const posts = files.map(filename => {
    const slug = filename.replace('.md', '')

    //get front matter
    const markedownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')

    const {data:frontmatter}= matter(markedownWithMeta)

    return {
      slug,
      frontmatter
    }
  })




  return { 
    props: {
      posts: posts.sort(sortByDate)
    }

  }
}


